name: Build and Upload APK

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Java and Gradle
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "export PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradlew
        run: chmod +x android/gradlew

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Move APK to Artifact Directory
        run: |
          mkdir -p release-apk
          mv android/app/build/outputs/apk/release/app-release.apk release-apk/app-release.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: release-apk/app-release.apk

      - name: Commit and Push APK to Repo
        run: |
          git config --global user.name "DevMosaicRakib"
          git config --global user.email "devmosaic17@gmail.com"
          git add release-apk/app-release.apk
          git commit -m "Automated APK build: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GA }}@github.com/DevMosaicRakib/staypure_android_app-React-Native-.git main

